concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "EXAMPLE"
  url = "EXAMPLE"
  id = 103
  clone_url = "EXAMPLE"
  token = "EXAMPLE"
  token_obtained_at = EXAMPLE
  token_expires_at = EXAMPLE
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "docker:24.0.5"
    privileged = true
    volumes = ["/certs/client", "/cache"]
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    shm_size = 0