services:
  app:
    container_name: dotnet-web-test
    build: .
    ports: 
        - 5051:80
    depends_on: [ postgres ]
  postgres:
    build: ./db_init
    user: "${POSTGRES_USER}"
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
